[workspace]
members = [
    "proc-macros",
    "resources",
    "server",
    "vau",
]
default-members = [
    "server"
]

[patch.crates-io]
actix-web = { git = "https://github.com/Gematik-Entwicklung/actix-web.git", branch = "ref-erx-fd-server-v3.0.2" }
openssl = { git = "https://github.com/Gematik-Entwicklung/rust-openssl.git", branch = "ref-erx-fd-server-v0.10.30" }
