[workspace]
members = [
    "libxml",
    "libxml-sys",
    "miscellaneous",
    "proc-macros",
    "resources",
    "server",
    "tool",
    "vau",
    "xmlsec",
]
default-members = [
    "server"
]

[patch.crates-io]
actix-web = { git = "https://github.com/Gematik-Entwicklung/actix-web.git", rev = "393813870e0342f9f9fb6818db90c8f8b6767f84" }
libxml = { path = "./libxml" }
libxml-sys = { path = "./libxml-sys" }
miscellaneous = { path = "./miscellaneous" }
openssl = { git = "https://github.com/Gematik-Entwicklung/rust-openssl.git", rev = "aa43dfc9198223c8408fc580e920198f3323db18" }
proc-macros = { path = "./proc-macros" }
resources = { path = "./resources" }
vau = { path = "./vau" }
xmlsec = { path = "./xmlsec" }
