[workspace]
members = [
    "miscellaneous",
    "proc-macros",
    "resources",
    "server",
    "tool",
    "vau",
]
default-members = [
    "server"
]

[patch.crates-io]
actix-web = { git = "https://github.com/Gematik-Entwicklung/actix-web.git", rev = "393813870e0342f9f9fb6818db90c8f8b6767f84" }
miscellaneous = { path = "./miscellaneous" }
openssl = { git = "https://github.com/Gematik-Entwicklung/rust-openssl.git", rev = "79c035916acde977686690a951e7a6712389b6a6" }
proc-macros = { path = "./proc-macros" }
resources = { path = "./resources" }
vau = { path = "./vau" }
