[package]
name = "resources"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
lazy_static = "1.4"
rand = "0.7"
regex = "1.3"
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "1.0"
uuid = { version = "0.8", features = [ "v1" ] }
